image: atlas/analysistop:latest

before_script:
  - mkdir -p ../ci/build ../ci/run ../ci/source/TopLoop
  - cp -r `pwd`/* ../ci/source/TopLoop/.
  - cp `pwd`/.gitlab-ci.cmake ../ci/source/CMakeLists.txt
  - cd ../ci/source

build:
  script:
    - ls
    - pwd
    - set +e
    - source /home/atlas/release_setup.sh
    - cd ../build
    - cmake ../source
    - make
    - cd ..
    - source build/*/setup.sh
