stages:
  - build
  - docgen
  - docdeploy

TopLoop:
  image: atlas/analysistop:latest
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SSL_NO_VERIFY: "true"
  before_script:
    - mkdir -p ../ci/build ../ci/run ../ci/source
    - cp -r $(pwd) ../ci/source/.
    - cp $(pwd)/.gitlab-ci.cmake ../ci/source/CMakeLists.txt
  script:
    - source /home/atlas/release_setup.sh
    - set +e
    - cd ../ci/build
    - cmake ../source
    - make
    - source "${AnalysisTop_PLATFORM}/setup.sh"

TopLoopDocGen:
  image: gitlab-registry.cern.ch/ddavis/doxygen-from-arch:latest
  stage: docgen
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SSL_NO_VERIFY: "true"
  script:
    - set +e
    - ls
    - doxygen doc/dox.cfg
    - mkdir public
    - mv doc/html public/TopLoopDoxygenAPI
    - cd doc
    - make html
    - mv build/html ../public/TopLoop
    - cd ..
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - master

TopLoopDocDeploy:
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  stage: docdeploy
  variables:
    GIT_STRATEGY: none
    DFS_WEBSITE_NAME: "twrun2"
  script:
    - set +e
    - deploy-dfs
  only:
    - master
