TopLoop:
  variables:
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  script:
    - ls
    - set +e
    - source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh
    - mkdir ../build
    - asetup 21.2,AnalysisTop,latest,here
    - cd ../build
    - cmake ../TopLoop
    - make
